---
title: "Problem Set 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Make sure your code is well-commented and reproducible. Unless stated in the problem, you can (and may need to) use some Google/StackExchange/ChatGPT searching to find how to code parts of your answers.

## Problem 1: Memory location


Let's learn about some of the nuances of memory allocation.

1. Generate one $20,000 \times 20,000$ array of random numbers named `x`. 
2. Make a function called `exp_cols` which exponentiates the elements of `x` column by column (i.e. by broadcasting `exp.()`) and returns the exponentiated array.
3. Make a function called `exp_rows` which exponentiates the elements of `x` row by row (i.e. by broadcasting `exp.()`) and returns the exponentiated array.
4. Call `exp_cols(x)` and `exp_rows(x)` twice and calculate the elapsed time and memory allocation on the second call (avoids fixed cost of initial compiliation).
5. Is one faster than the other?
6. If you exponentiate the full array instead of looping column-by-column or row-by-row how does it compare?

## Problem 2: Newton

Consider a Cournot duopoly where aggregate inverse demand is given by $P(q) = q^{-1/\eta}$, $q = q_1 + q_2$, and the firm cost functions are $C_1(q_1) = 0.5 c_1 q_1^2, C_2(q_2) = 0.5 c_2 q^2_2$. 

1. Write your own Newton's method solver for this general problem: `cournot_newton(eta, c1, c2, initial_guess, tolerance)`.

Hint: think about the first-order conditions and best response functions.

2. Solve for the equilibrium outcome using Newton's method for $\eta = 1.6, c_1 = .15, c_2 = 0.2$.


## Problem 3: Newton + MLE

Write a function `mle_newton(x, y, theta, tol)` that estimates the parameters $\theta$ of a linear model using maximum likelihood. $x$ is an $N \times K$ matrix of $K$ explanatory variables, $y$ is an $N \times 1$ vector of the outcome variable. $Y = X \theta + \varepsilon$ where $\varepsilon$ is an iid normally distributed noise term. The function should return the central estimate of $\theta$ as well as bootstrapped standard errors.

## Problem 4: Optimization packages

Suppose a consumer has the following CES utility:
$$u(C_1, C_2) = (\kappa C_1^{(\eta - 1)/\eta} + (1-\kappa) C_2^{(\eta - 1)/\eta} ) ^{\eta/(\eta-1)}$$
and faces a budget of
$$ p_1 C_1 + p_2 C_2 = W$$

1. Recast the problem as an unconstrained utility maximization problem.
2. Use the `Optim` or `JuMP` package and write a program   
`utility_maximizer(kappa, eta, p1, p2, w, initial_guess)` to solve this utility maximization problem.
    
Feel free to use the default settings (tolerances, etc) for the optimization package or change them. Here's a hint if you run into issues with negative numbers: replace the variable `X` in the function with `exp(X)`, which is strictly positive. This lets the solver search over arbitrary real-valued `X` without imposing a non-negativity constraint.

3. Choose a set of parameters and solve it analytically. Also solve it numerically with the same set of parameters and report the algorithm results (e.g. the output shown [here](https://julianlsolvers.github.io/Optim.jl/stable/#algo/cg/)).
   - Note: Let $0 < \kappa < 1$ and $\eta > 1$